spring.application.name=cadastro-usuario

# Configurações do Console do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configurações do Banco de Dados (CORRIGIDO: mem em vez de men)
spring.datasource.url=jdbc:h2:mem:usuario
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=1234

# Configurações do Hibernate (Importante para o H2 em memória)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Porta do Servidor
server.port=8081  
